#!/bin/bash  

#./determine_cutoff.py --input_dir /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP01Tr20_Fr3_MP02Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP01Tr20_Fr3_MP03Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP01Tr20_Fr3_MP04Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP01Tr20_Fr3_MP05Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP01Tr20_Fr3_MP06Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP01Tr20_Fr3_MP07Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP01Tr20_Fr3_MP08Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP01Tr20_Fr3_MP09Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP01Tr20_Fr3_MP72Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP01Tr20_Fr3_MP82Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP01Tr20_Fr3_MP92Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP03Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP04Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP05Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP06Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP07Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP08Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP09Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP72Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP82Tr20_Fr3/data/output/ /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP92Tr20_Fr3/data/output/ --unsel MP --output_pre ./

#./corr_counts.py --ratios_file1 /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP01Tr20_Fr3_MP02Tr20_Fr3/data/output/ratios_MP02Tr20_Fr3.fast_R1_PRO_qc_MP01Tr20_Fr3.fast_R1_PRO_qc --ratios_file2 /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP03Tr20_Fr3/data/output/ratios_MP03Tr20_Fr3.fast_R1_PRO_qc_MP02Tr20_Fr3.fast_R1_PRO_qc --output_pre ./ --use_unsel

./corr_counts.py --ratios_file1 /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP07Tr20_Fr3/data/output/ratios_MP07Tr20_Fr3.fast_R1_PRO_qc_MP02Tr20_Fr3.fast_R1_PRO_qc --ratios_file2 /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP72Tr20_Fr3/data/output/ratios_MP72Tr20_Fr3.fast_R1_PRO_qc_MP02Tr20_Fr3.fast_R1_PRO_qc --output_pre ./ --use_sel    &

./corr_counts.py --ratios_file1 /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP08Tr20_Fr3/data/output/ratios_MP08Tr20_Fr3.fast_R1_PRO_qc_MP02Tr20_Fr3.fast_R1_PRO_qc --ratios_file2 /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP82Tr20_Fr3/data/output/ratios_MP82Tr20_Fr3.fast_R1_PRO_qc_MP02Tr20_Fr3.fast_R1_PRO_qc --output_pre ./ --use_sel     &

./corr_counts.py --ratios_file1 /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP09Tr20_Fr3/data/output/ratios_MP09Tr20_Fr3.fast_R1_PRO_qc_MP02Tr20_Fr3.fast_R1_PRO_qc --ratios_file2 /Users/arubenstein/git_repos/deep_seq/processing_seqs/results/enrich/unfiltered/MP02Tr20_Fr3_MP92Tr20_Fr3/data/output/ratios_MP92Tr20_Fr3.fast_R1_PRO_qc_MP02Tr20_Fr3.fast_R1_PRO_qc --output_pre ./ --use_sel    & 
