#!/bin/bash

python CreateEdges.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved_fitness.csv "CLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_uncleaved_fitness.csv "UNCLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_middle_fitness.csv "MIDDLE" --hamming_dist 1 --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq --canonical_file ~/git_repos/deep_seq/analysis_vis/canonical_seqs.txt

python CreateEdges.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_cleaved_fitness.csv "CLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_uncleaved_fitness.csv "UNCLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_middle_fitness.csv "MIDDLE" --hamming_dist 1 --output_prefix ~/git_repos/deep_seq/analysis_vis/results/graph_inputs/011 --canonical_file ~/git_repos/deep_seq/analysis_vis/canonical_seqs.txt

python CreateEdges.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_cleaved_fitness.csv "CLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_uncleaved_fitness.csv "UNCLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_middle_fitness.csv "MIDDLE" --hamming_dist 1 --output_prefix ~/git_repos/deep_seq/analysis_vis/results/graph_inputs/021 --canonical_file ~/git_repos/deep_seq/analysis_vis/canonical_seqs.txt

python CreateEdges.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/091_cleaved_fitness.csv "CLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/091_uncleaved_fitness.csv "UNCLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/091_middle_fitness.csv "MIDDLE" --hamming_dist 1 --output_prefix ~/git_repos/deep_seq/analysis_vis/results/graph_inputs/091 --canonical_file ~/git_repos/deep_seq/analysis_vis/canonical_seqs.txt

python CreateEdges.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/101_cleaved_fitness.csv "CLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/101_uncleaved_fitness.csv "UNCLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/101_middle_fitness.csv "MIDDLE" --hamming_dist 1 --output_prefix ~/git_repos/deep_seq/analysis_vis/results/graph_inputs/101 --canonical_file ~/git_repos/deep_seq/analysis_vis/canonical_seqs.txt

#just cleaved graph
python CreateEdges.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved_fitness.csv "CLEAVED" --hamming_dist 1 --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq --canonical_file ~/git_repos/deep_seq/analysis_vis/canonical_seqs.txt

python FractionFuncPerMutant.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved.txt "CLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_uncleaved.txt "UNCLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_middle.txt "MIDDLE" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq_cleaved_v_uncleaved --func_labels "CLEAVED" --unfunc_labels "UNCLEAVED" --canonical "DEMEE" 

python FractionFuncPerMutant.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved.txt "CLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_uncleaved.txt "UNCLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_middle.txt "MIDDLE" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq_cleaved_v_uncleaved_middle --func_labels "CLEAVED" --unfunc_labels "UNCLEAVED" "MIDDLE" --canonical "DEMEE"

python FractionFuncPerMutant.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved.txt "CLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_uncleaved.txt "UNCLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_middle.txt "MIDDLE" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq_cleaved_middle_v_uncleaved --func_labels "CLEAVED" "MIDDLE" --unfunc_labels "UNCLEAVED" --canonical "DEMEE"

python FractionFunctional.py --seq_file ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved.txt --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq_cleaved_v_uncleaved --canonical "DEMEE"

python FractionNeighborsUncleaved.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved.txt "CLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_uncleaved.txt "UNCLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_middle.txt "MIDDLE" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq_ 

python VennDiagram.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/101_cleaved.txt "R155K" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_cleaved.txt "A156T" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/091_cleaved.txt "D186A" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq

python VennDiagram.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_cleaved.txt "KTA" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_cleaved.txt "A156T" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/091_cleaved.txt "D186A" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq

python VennDiagram.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_cleaved.txt "KTA" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/101_cleaved.txt "R155K" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/091_cleaved.txt "D186A" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq

python VennDiagram.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_cleaved.txt "KTA" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_cleaved.txt "A156T" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved.txt "WT" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq

python VennDiagram.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_uncleaved.txt "KTA_uncleaved" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_uncleaved.txt "A156T_uncleaved" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_uncleaved.txt "WT_uncleaved" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq

python VennDiagram.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved.txt "WT cleaved" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_cleaved.txt "KTA cleaved" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_uncleaved.txt "WT uncleaved" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq

python VennDiagram.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved.txt "WT cleaved" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_uncleaved.txt "KTA uncleaved" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_uncleaved.txt "WT uncleaved" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq

python FindSeqs.py --input_dir ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/ --output_prefix ./ --hamm_dist -1 --canonical_file ~/git_repos/deep_seq/analysis_vis/canonical_seqs.txt 

python EpistasisAllSeqs.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved_fitness_ratio.csv "CLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_uncleaved_fitness_ratio.csv "UNCLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_middle_fitness_ratio.csv "MIDDLE" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/WT_nextseq

python ProtEpistasisAllSeqs.py --start_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved_fitness_ratio.csv "CLEAVED" --start_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_uncleaved_fitness_ratio.csv "UNCLEAVED" --start_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_middle_fitness_ratio.csv "MIDDLE" --inter1_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_cleaved_fitness_ratio.csv "CLEAVED" --inter1_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_uncleaved_fitness_ratio.csv "UNCLEAVED" --inter1_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_middle_fitness_ratio.csv "MIDDLE" --inter2_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/091_cleaved_fitness_ratio.csv "CLEAVED" --inter2_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/091_uncleaved_fitness_ratio.csv "UNCLEAVED" --inter2_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/091_middle_fitness_ratio.csv "MIDDLE" --inter3_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/101_cleaved_fitness_ratio.csv "CLEAVED" --inter3_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/101_uncleaved_fitness_ratio.csv "UNCLEAVED" --inter3_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/101_middle_fitness_ratio.csv "MIDDLE" --end_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_cleaved_fitness_ratio.csv "CLEAVED" --end_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_uncleaved_fitness_ratio.csv "UNCLEAVED" --end_sequences ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_middle_fitness_ratio.csv "MIDDLE" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/variants/variants --inter_muts TAK

python CleavedUncleavedMiddle.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved_fitness_ratio.csv "CLEAVED" "WT" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_uncleaved_fitness_ratio.csv "UNCLEAVED" "WT" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_middle_fitness_ratio.csv "MIDDLE" "WT" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_cleaved_fitness_ratio.csv "CLEAVED" "A156T" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_uncleaved_fitness_ratio.csv "UNCLEAVED" "A156T" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/021_middle_fitness_ratio.csv "MIDDLE" "A156T" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/091_cleaved_fitness_ratio.csv "CLEAVED" "D186A" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/091_uncleaved_fitness_ratio.csv "UNCLEAVED" "D186A" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/091_middle_fitness_ratio.csv "MIDDLE" "D186A" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/101_cleaved_fitness_ratio.csv "CLEAVED" "R155K" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/101_uncleaved_fitness_ratio.csv "UNCLEAVED" "R155K" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/101_middle_fitness_ratio.csv "MIDDLE" "R155K" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_cleaved_fitness_ratio.csv "CLEAVED" "KTA" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_uncleaved_fitness_ratio.csv "UNCLEAVED" "KTA" --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/011_middle_fitness_ratio.csv "MIDDLE" "KTA" --output_prefix ~/git_repos/deep_seq/analysis_vis/results/variants/variants

./extract_data_seq_categorize.sh ~/Dropbox/Research/Khare/deep_seq/norm_counts11/summary_WT_nextseq.csv

python convert_seq_features.py --sequence_list ~/git_repos/deep_seq/analysis_vis/seq_lists_norm_counts11/WT_nextseq_cleaved.txt --conversion_type alpha

python PlotEpistasisDist.py --epistasis results/epistasis/WT_nextseq_epi.csv

python PlotMod.py --list_nodes results/graph_outputs/WT_nextseq_DEMEE_1_1-5_2_cleaved_modularity_3.csv --output_prefix results/graph_figures/WT_nextseq_DEMEE_1_1-5_2_cleaved_modularity

python PlotMetrics.py --list_nodes results/graph_outputs/WT_nextseq_DEMEE_1_1-5_2.csv --output_prefix results/graph_figures/WT_nextseq_DEMEE_1_1-5_2 --metric metrics

python PromisPlotMetrics.py --list_nodes results/graph_outputs/WT_nextseq_DEMEE_1_1-5_2.csv "WT" --list_nodes results/graph_outputs/011_DEMEE_1_1-5_2.csv "011" --list_nodes results/graph_outputs/021_DEMEE_1_1-5_2.csv "021" --list_nodes results/graph_outputs/091_DEMEE_1_1-5_2.csv "091" --list_nodes results/graph_outputs/101_DEMEE_1_1-5_2.csv "101" --output_prefix results/graph_figures/variants --metric metrics


awk -F, -v l=$label 'BEGIN{OFS=","}; {for (i=2; i<=NF; i++) printf $i","}{print "0,0,0,0",l}'  011_cleaved_sequence_features_binary.csv > 011_cleaved_structseq_binary.csv

python FractionShellsRaw.py --sequence_list /Users/arubenstein/git_repos/deep_seq/analysis_vis/svm_results/cleaved_seqs_svm_structseq.list "CLEAVED" --sequence_list /Users/arubenstein/git_repos/deep_seq/analysis_vis/svm_results/uncleaved_seqs_svm_structseq.list "UNCLEAVED" --output_prefix /Users/arubenstein/git_repos/deep_seq/analysis_vis/results/fraction_shells

python CreateEdgesNX.py --sequence_list ~/git_repos/deep_seq/analysis_vis/svm_results/cleaved_seqs_svm_structseq.txt "CLEAVED" --sequence_list ~/git_repos/deep_seq/analysis_vis/svm_results/uncleaved_seqs_svm_structseq.txt "UNCLEAVED" --hamming_dist 1 --output_prefix ~/git_repos/deep_seq/analysis_vis/results/graph_inputs/SVM_fullNX --canonical_file ""

python ShortestPaths.py --json_file ~/git_repos/deep_seq/analysis_vis/results/graph_inputs/SVM_fullNXcleaved_nodes_edges.json --output_prefix ~/git_repos/deep_seq/analysis_vis/results/shortest --source 'DEMEE' --target 'AEMIE'

python FindNovelClusters.py --json_file ~/git_repos/deep_seq/analysis_vis/results/graph_inputs/SVM_full_cleaved_NXnodes_edges.json --nbunch_file ~/git_repos/deep_seq/analysis_vis/results/svm_cleavedcanonical_sim_cleaved_more_3.csv --output_prefix ~/git_repos/deep_seq/analysis_vis/results/svm_cleavedcanonical_sim_cleaved_more_3

python FindSeqs.py --input_file ~/git_repos/deep_seq/analysis_vis/svm_results/cleaved_seqs_svm_structseq.txt --canonical_file ~/git_repos/deep_seq/analysis_vis/input/canonical_seqs.txt --output_prefix ~/git_repos/deep_seq/analysis_vis/results/svm_analysis/svm_cleaved --hamm_dist 2 --more_than 
